
name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [i686, aarch64]
    steps:
    - uses: actions/checkout@v1
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install build-essential flex bison
        sudo apt-get install texinfo wget mtools
        sudo apt-get install libmpc-dev libgmp-dev libmpfr-dev
        sudo apt-get install grub-common nasm
    - uses: actions/cache@v1
      id: cache
      with:
        path: toolchain
        key: toolchain-${{ matrix.arch }}

    - name: Build toolchain ${{ matrix.arch }}
      run: ARCH=${{ matrix.arch }} ./scripts/build_toolchain.sh

    - name: Build Fukuro ${{ matrix.arch }}
      run: ARCH=${{ matrix.arch }} make

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install test dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential libcmocka-dev
      - name: Build and run tests
        run: make test
